name: build

on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gradle Build
      run: ./gradlew build
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - name: Post Result
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        git clone https://github.com/CominAtYou/github-actions-discord-webhook webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash
